In [1]:
import numpy as np
print(np.__version__)

1.22.3


1

In [2]:
L = [ 12.23, 13.32, 100., 36.32]
oneDarr=np.array(L).reshape((1,len(L)))
print(oneDarr.shape)

(1, 4)


2

In [3]:
out = np.array(range(2,11)).reshape((3,3))
print(out)
out.shape

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


(3, 3)

3

In [4]:
arr = np.zeros(10)
arr[5] = 11.
print(arr)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


4

In [5]:
out = np.arange(12,38)
print(out)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


5

In [6]:
out = np.arange(12,38)[::-1]
print(out)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


6

In [7]:
out = np.asfarray(range(1,5))
print(out)

[1. 2. 3. 4.]


7

In [8]:
ones_matrix = np.ones((7,5))
ones_matrix[1:-1,1:-1] = 0
out = ones_matrix
print(out)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


8

In [9]:
arr = np.ones((3, 3))
out = np.pad(arr, pad_width=(1, 1), mode='constant', constant_values=0)
print(out)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


9

In [10]:
arr = np.ones((8,8))
arr[::2, ::2] = 0.
arr[1::2, 1::2] = 0.
out = arr
print(out)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


10

In [11]:
out1 = np.asarray(range(8))+1
out2 = np.asarray([[8, 4, 6], [1, 2, 3]])
print(out1, out2)

[1 2 3 4 5 6 7 8] [[8 4 6]
 [1 2 3]]


11

In [12]:
arr = np.array([10, 20, 30])
out = np.append(arr, [arr+30, arr+60])
print(out)

[10 20 30 40 50 60 70 80 90]


12

In [13]:
arr = np.array([-17.77777778, -11.11111111, 7.33888889, 1.1111111, 37.72777778])
def degC_to_degF(arr_in_C):
    return ((9.*arr_in_C) + (32.*5.))/5
out = degC_to_degF(arr)
out = np.round(out, 2)
print(out)


[-0.   12.   45.21 34.   99.91]


13

In [14]:
def get_arrinfo(arr):
    print('array contains', arr.size, 'elements')
    print('first item is', arr[0].itemsize, 'bytes')
    print('array takes up', arr.nbytes, 'bytes')
get_arrinfo(np.array([1, 2, 3]))
#print(out)

array contains 3 elements
first item is 4 bytes
array takes up 12 bytes


14

In [15]:
def arr_intersection(arr1, arr2):
    L1, L2 = arr1.flatten(), arr2.flatten()
    arr3 = np.array([el for el in L1 if el in L2])
    return arr3
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40])
out = arr_intersection(array1, array2)
print(out)

[10 40]


15

In [16]:
arr1 = np.array([10, 10, 20, 20, 30, 30])
arr2 = np.array([[1, 1], [2, 3]])
def uniquify_arr(arr):  
    """returns an unsorted array of unique elements"""
    return np.array(list(set(arr.flatten())))
print(arr1, '->', uniquify_arr(arr1))
print(arr2, '->', uniquify_arr(arr2))

[10 10 20 20 30 30] -> [10 20 30]
[[1 1]
 [2 3]] -> [1 2 3]


16

In [17]:
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70])
def A_excluding_B(arrA, arrB):
    A = uniquify_arr(arrA)
    B = uniquify_arr(arrB)
    print('array 1 =', arrA, '; array2 =', arrB)
    arr_out = np.array([el for el in A if el not in B])
    print('vals in array 1, excluding vals in array 2 =', arr_out, '\n')
    return np.sort(arr_out)
out = A_excluding_B(arr1, arr2)


array 1 = [ 0 10 20 40 60 80] ; array2 = [10 30 40 50 70]
vals in array 1, excluding vals in array 2 = [ 0 80 20 60] 



17

In [18]:
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70])
def vals_exclusive_to_one_arr(arrA, arrB):
    arrout = np.append(A_excluding_B(arrA, arrB), A_excluding_B(arrB, arrA))
    print('arrays = {', arrA, ',', arrB, '}')
    print('vals unique to exactly one array =', arrout)
    return(arrout)
out = vals_exclusive_to_one_arr(arr1, arr2)


array 1 = [ 0 10 20 40 60 80] ; array2 = [10 30 40 50 70]
vals in array 1, excluding vals in array 2 = [ 0 80 20 60] 

array 1 = [10 30 40 50 70] ; array2 = [ 0 10 20 40 60 80]
vals in array 1, excluding vals in array 2 = [70 50 30] 

arrays = { [ 0 10 20 40 60 80] , [10 30 40 50 70] }
vals unique to exactly one array = [ 0 20 60 80 30 50 70]


18

In [19]:
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70])
def arr_union(arrA, arrB):
    appendAB = np.append(arrA.flatten(), arrB.flatten())
    return np.sort(uniquify_arr(appendAB))
print(arr_union(arr1, arr2))

[ 0 10 20 30 40 50 60 70 80]


19

In [20]:
bools_true = np.arange(1,11)>0
bools = bools_true.copy()
bools[0:2] = [0, False]
def contains_no_falses(arr):
    if False in arr or 0 in arr:
        return False
    else:
        return True
out1 = contains_no_falses(bools)
out2 = contains_no_falses(bools_true)
print(out1, out2)

False True


20

In [21]:
np.where(np.array([[0,0,1],[0,1,0],[0,0,0]]))[0]

array([0, 1], dtype=int64)

In [22]:
def whereis_el(arr, el):
    if arr.ndim == 1:
        arr = arr.reshape((1, arr.size))
    rows_w_el,cols_w_el = np.where(arr == el)
    return list(zip(rows_w_el,cols_w_el))

def whereis_minmax(arr):
    """returns indecies of min and max values in arr"""
    elementlist = np.sort(uniquify_arr(arr))
    min = elementlist[0]
    max = elementlist[-1]
    print('array:\n', arr)
    print('min =', min,'@',
        whereis_el(arr,min))
    print('max =', max, '@',
        whereis_el(arr,max))

ar1=np.array([1,1,0,1,6,2,2,0])
ar2=np.array([[1,1,0,1,1,2,2,0]])
ar3=np.array([[1,1,0,1,1,2,1,0],[1,1,0,1,1,2,2,0]])

whereis_minmax(ar1)
whereis_minmax(ar2)
whereis_minmax(ar3)

array:
 [1 1 0 1 6 2 2 0]
min = 0 @ [(0, 2), (0, 7)]
max = 6 @ [(0, 4)]
array:
 [[1 1 0 1 1 2 2 0]]
min = 0 @ [(0, 2), (0, 7)]
max = 2 @ [(0, 5), (0, 6)]
array:
 [[1 1 0 1 1 2 1 0]
 [1 1 0 1 1 2 2 0]]
min = 0 @ [(0, 2), (0, 7), (1, 2), (1, 7)]
max = 2 @ [(0, 5), (1, 5), (1, 6)]


21

In [23]:
def whereis_true(boolarr):
    if boolarr.ndim == 1:
        boolarr = boolarr.reshape((1, boolarr.size))
    rows,cols = np.where(boolarr)
    return list(zip(rows,cols))

arr = np.array([[0,10,20],[20,30,40]])
indecies=whereis_true(arr>10)

for index in indecies:
    print(arr[index],'@', index)

20 @ (0, 2)
20 @ (1, 0)
30 @ (1, 1)
40 @ (1, 2)


22

In [24]:

print(np.zeros(2),np.ones(2))

[0. 0.] [1. 1.]


23

In [25]:
arr = np.array([[10, 20, 30], [20, 40, 50]])
print(arr.flatten())

[10 20 30 20 40 50]


24

In [26]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print(arr.reshape((3,2)))

[[10 20]
 [30 40]
 [50 60]]


25

In [27]:
np.array([[1, 2, 3], [4, 5, 6]]).astype(float)
#print(out)

array([[1., 2., 3.],
       [4., 5., 6.]])

26

In [28]:
out = np.logspace(np.log10(2.), np.log10(5.), 20, endpoint = False, base=10)
print(out)

[2.         2.09376047 2.19191645 2.29467401 2.40224887 2.51486686
 2.63276441 2.75618902 2.88539981 3.02066803 3.16227766 3.31052598
 3.46572422 3.62819818 3.79828896 3.97635364 4.16276604 4.35791749
 4.56221768 4.77609552]


27

In [29]:
arr1 = [[0, 1, 3], [5, 7, 9]]
arr2 = [[0, 2, 4], [6, 8, 10]]
out = np.concatenate((arr1, arr2), axis = 1)
print(out)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


28

In [30]:
arr0 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
out = (np.split(arr0, [2,6]))
print(out)

[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


29

In [31]:
arr0 = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
out = np.split(arr0, 2, axis=1)
print(out[0],'\n', out[1])

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


30

In [32]:
arr = [[ 0, 10, 20], [20, 30, 40]]
out = np.count_nonzero(arr)
print(out)

5


31

In [33]:
arr = [[ 0, 10, 20], [30, 40, 50]]
out = np.append(arr, [[100], [200]], axis = 1)
print(out)

[[  0  10  20 100]
 [ 30  40  50 200]]


32

In [34]:
arr = np.array([[ 1, -10, 20], [-30, 40, 50]])
out = arr * (arr>0).astype(int)
print(out)

[[ 1  0 20]
 [ 0 40 50]]


33

In [35]:
import pandas as pd
arr = np.array([[ 1, -10, 20], [-30, 40, 50], [np.NaN, 2, 4]])
out1 = np.array([v for v in arr if not np.isnan(v).any()])
out2 = np.array([v for v in arr if not pd.isna(v).any()])

print(out1,'\n', out2)

[[  1. -10.  20.]
 [-30.  40.  50.]] 
 [[  1. -10.  20.]
 [-30.  40.  50.]]


34

In [36]:
a = np.array([97, 101, 105, 111, 117]) 
b = np.array(['a','e','i','o','u'])
out = [L[1] for L in enumerate(b) if (100 < a[L[0]] and a[L[0]] < 110) ]
print(out)

['e', 'i']


35

In [37]:
arr = np.array([10, 10, 20, 10, 20, 20, 20, 30, 30, 50, 40, 40])
vals = np.sort(uniquify_arr(arr))
out = np.array([[val, np.sum(arr==val)] for val in vals])
print(out)

[[10  3]
 [20  4]
 [30  2]
 [40  2]
 [50  1]]


36

In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
out = arr[:,-2:]
print(out)

[[2 3]
 [5 6]
 [8 9]]


37

In [39]:
arr = np.array([1, 0, 2, 0, 3, 0, 4, 5, 6, 7, 8])

out = np.array([x[0] for x in enumerate(arr) if x[1]==0])
print(out)
#alternatively:
print(np.where(arr==0)[0])

[1 3 5]
[1 3 5]
